### ISSUE TITLE
Dubious compression when top = 2**64 - 1

### ISSUE THREAD

**Issue by rmn30** [CTSRD-CHERI/cheri-compressed-cap#1]
I noticed the following this dubious code in compress_128cap:
https://github.com/CTSRD-CHERI/cheri-compressed-cap/blob/003e29ed2052ba38a26ec84b08baca62bcfa9b5c/cheri_compressed_cap.h#L301
It appears to imply that any capability whose top is `2**64 - 1` will be treated as though it is actually `2**64`. I suppose this is required to cope with the fact that the default cap has length `2**64` and qemu is using 64-bit arithmetic but it breaks capability monotonicity. If I create a capability whose top is `2**64 - 1` will it magically gain access to an extra byte!?

There is similar code at https://github.com/CTSRD-CHERI/cheri-compressed-cap/blob/003e29ed2052ba38a26ec84b08baca62bcfa9b5c/cheri_compressed_cap.h#L430

**Comment by LawrenceEsswood** [comment]
Yeah exactly this. The issue arrises because we store the length (rather than top and bottom) in qemu. This means we need a 65 bit field but that would have required changing a lot of code. The result was that hack.


Sent from my Samsung device

-------- Original message --------

**Comment by rmn30** [comment]
OK, that's probably an acceptable approximation for Qemu but good for it to be documented somewhere and should maybe even have an xfail test for it.

**Comment by arichardson** [comment]
Should be fixed now that the compression is derived from the sail code.
